// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { StakingPool$Type } from "./StakingPool";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["StakingPool"]: StakingPool$Type;
    ["contracts/StakingPool.sol:StakingPool"]: StakingPool$Type;
  }

  interface ContractTypesMap {
    ["StakingPool"]: GetContractReturnType<StakingPool$Type["abi"]>;
    ["contracts/StakingPool.sol:StakingPool"]: GetContractReturnType<StakingPool$Type["abi"]>;
  }
}
