// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ILuminaCoin$Type } from "./ILuminaCoin";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ILuminaCoin"]: ILuminaCoin$Type;
    ["contracts/interfaces/ILuminaCoin.sol:ILuminaCoin"]: ILuminaCoin$Type;
  }

  interface ContractTypesMap {
    ["ILuminaCoin"]: GetContractReturnType<ILuminaCoin$Type["abi"]>;
    ["contracts/interfaces/ILuminaCoin.sol:ILuminaCoin"]: GetContractReturnType<ILuminaCoin$Type["abi"]>;
  }
}
