// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ILuminaCoin$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ILuminaCoin",
  "sourceName": "contracts/interfaces/ILuminaCoin.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "spender",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "approve",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "from",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "burn",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "to",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "mint",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "sender",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "recipient",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "transferFrom",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ILuminaCoin",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ILuminaCoin$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/interfaces/ILuminaCoin.sol:ILuminaCoin",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ILuminaCoin$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ILuminaCoin",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ILuminaCoin$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/interfaces/ILuminaCoin.sol:ILuminaCoin",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ILuminaCoin$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ILuminaCoin",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ILuminaCoin$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/interfaces/ILuminaCoin.sol:ILuminaCoin",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ILuminaCoin$Type["abi"]>>;
}
