/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernanceToken__factory } from "./GovernanceToken__factory";
export { Lock__factory } from "./Lock__factory";
export { MyGovernor__factory } from "./MyGovernor__factory";
