/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernanceToken } from "./GovernanceToken";
export type { Lock } from "./Lock";
export type { MyGovernor } from "./MyGovernor";
