// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { CollateralManager$Type } from "./CollateralManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CollateralManager"]: CollateralManager$Type;
    ["contracts/CollateralManager.sol:CollateralManager"]: CollateralManager$Type;
  }

  interface ContractTypesMap {
    ["CollateralManager"]: GetContractReturnType<CollateralManager$Type["abi"]>;
    ["contracts/CollateralManager.sol:CollateralManager"]: GetContractReturnType<CollateralManager$Type["abi"]>;
  }
}
