/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IName,
  INameInterface,
} from "../../FuzzyIdentityChallenge.sol/IName";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "name",
    outputs: [
      {
        name: "",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class IName__factory {
  static readonly abi = _abi;
  static createInterface(): INameInterface {
    return new utils.Interface(_abi) as INameInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IName {
    return new Contract(address, _abi, signerOrProvider) as IName;
  }
}
