/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FuzzyIdentityChallenge__factory } from "./FuzzyIdentityChallenge__factory";
export { IName__factory } from "./IName__factory";
