/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FuzzyIdentityChallenge } from "./FuzzyIdentityChallenge";
export type { IName } from "./IName";
