/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type {
  AssumeOwnershipChallenge,
  AssumeOwnershipChallengeInterface,
} from "../AssumeOwnershipChallenge";

const _abi = [
  {
    constant: false,
    inputs: [],
    name: "AssumeOwmershipChallenge",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [],
    name: "authenticate",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "isComplete",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6060604052341561000f57600080fd5b6101ac8061001e6000396000f300606060405260043610610057576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806321aa06151461005c578063380c7a6714610071578063b2fa1c9e14610086575b600080fd5b341561006757600080fd5b61006f6100b3565b005b341561007c57600080fd5b6100846100f5565b005b341561009157600080fd5b61009961016d565b604051808215151515815260200191505060405180910390f35b336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614151561015057600080fd5b6001600060146101000a81548160ff021916908315150217905550565b600060149054906101000a900460ff16815600a165627a7a72305820c7f09d8c88e67e548949e8a24849ba06f9ac66a6595d027922097c0164e6784e0029";

type AssumeOwnershipChallengeConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AssumeOwnershipChallengeConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AssumeOwnershipChallenge__factory extends ContractFactory {
  constructor(...args: AssumeOwnershipChallengeConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<AssumeOwnershipChallenge> {
    return super.deploy(overrides || {}) as Promise<AssumeOwnershipChallenge>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): AssumeOwnershipChallenge {
    return super.attach(address) as AssumeOwnershipChallenge;
  }
  override connect(signer: Signer): AssumeOwnershipChallenge__factory {
    return super.connect(signer) as AssumeOwnershipChallenge__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AssumeOwnershipChallengeInterface {
    return new utils.Interface(_abi) as AssumeOwnershipChallengeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AssumeOwnershipChallenge {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as AssumeOwnershipChallenge;
  }
}
