/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  PayableOverrides,
} from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type {
  GuessTheNewNumberChallenge,
  GuessTheNewNumberChallengeInterface,
} from "../GuessTheNewNumberChallenge";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "n",
        type: "uint8",
      },
    ],
    name: "guess",
    outputs: [],
    payable: true,
    stateMutability: "payable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "isComplete",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    payable: true,
    stateMutability: "payable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6060604052670de0b6b3a76400003414151561001a57600080fd5b610189806100296000396000f30060606040526004361061004c576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680634ba4c16b14610051578063b2fa1c9e1461006c575b600080fd5b61006a600480803560ff16906020019091905050610099565b005b341561007757600080fd5b61007f61013c565b604051808215151515815260200191505060405180910390f35b6000670de0b6b3a7640000341415156100b157600080fd5b6001430340426040518083600019166000191681526020018281526020019250505060405180910390206001900490508060ff168260ff161415610138573373ffffffffffffffffffffffffffffffffffffffff166108fc671bc16d674ec800009081150290604051600060405180830381858888f19350505050151561013757600080fd5b5b5050565b6000803073ffffffffffffffffffffffffffffffffffffffff1631149050905600a165627a7a723058200e9f3a00baa5859d5073ae7fd5f4186408187872873d07aebffaa2eb53beebb50029";

type GuessTheNewNumberChallengeConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GuessTheNewNumberChallengeConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GuessTheNewNumberChallenge__factory extends ContractFactory {
  constructor(...args: GuessTheNewNumberChallengeConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<GuessTheNewNumberChallenge> {
    return super.deploy(overrides || {}) as Promise<GuessTheNewNumberChallenge>;
  }
  override getDeployTransaction(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): GuessTheNewNumberChallenge {
    return super.attach(address) as GuessTheNewNumberChallenge;
  }
  override connect(signer: Signer): GuessTheNewNumberChallenge__factory {
    return super.connect(signer) as GuessTheNewNumberChallenge__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GuessTheNewNumberChallengeInterface {
    return new utils.Interface(_abi) as GuessTheNewNumberChallengeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GuessTheNewNumberChallenge {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as GuessTheNewNumberChallenge;
  }
}
