/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  PayableOverrides,
} from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type {
  GuessTheSecretNumberChallenge,
  GuessTheSecretNumberChallengeInterface,
} from "../GuessTheSecretNumberChallenge";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "n",
        type: "uint8",
      },
    ],
    name: "guess",
    outputs: [],
    payable: true,
    stateMutability: "payable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "isComplete",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    payable: true,
    stateMutability: "payable",
    type: "constructor",
  },
];

const _bytecode =
  "0x60606040527fdb81b4d58595fbbbb592d3661a34cdca14d7ab379441400cbfa1b78bc447c365600102600090600019169055670de0b6b3a76400003414151561004757600080fd5b610197806100566000396000f30060606040526004361061004c576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680634ba4c16b14610051578063b2fa1c9e1461006c575b600080fd5b61006a600480803560ff16906020019091905050610099565b005b341561007757600080fd5b61007f61014a565b604051808215151515815260200191505060405180910390f35b670de0b6b3a7640000341415156100af57600080fd5b6000546000191681604051808260ff1660ff167f01000000000000000000000000000000000000000000000000000000000000000281526001019150506040518091039020600019161415610147573373ffffffffffffffffffffffffffffffffffffffff166108fc671bc16d674ec800009081150290604051600060405180830381858888f19350505050151561014657600080fd5b5b50565b6000803073ffffffffffffffffffffffffffffffffffffffff1631149050905600a165627a7a72305820c2c113a51787abaad06530ca0f553b3a3f6c08e98c3f56d406509233b9677e8a0029";

type GuessTheSecretNumberChallengeConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GuessTheSecretNumberChallengeConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GuessTheSecretNumberChallenge__factory extends ContractFactory {
  constructor(...args: GuessTheSecretNumberChallengeConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<GuessTheSecretNumberChallenge> {
    return super.deploy(
      overrides || {}
    ) as Promise<GuessTheSecretNumberChallenge>;
  }
  override getDeployTransaction(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): GuessTheSecretNumberChallenge {
    return super.attach(address) as GuessTheSecretNumberChallenge;
  }
  override connect(signer: Signer): GuessTheSecretNumberChallenge__factory {
    return super.connect(signer) as GuessTheSecretNumberChallenge__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GuessTheSecretNumberChallengeInterface {
    return new utils.Interface(_abi) as GuessTheSecretNumberChallengeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GuessTheSecretNumberChallenge {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as GuessTheSecretNumberChallenge;
  }
}
