/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITokenReceiver } from "./ITokenReceiver";
export type { SimpleERC223Token } from "./SimpleERC223Token";
export type { TokenBankChallenge } from "./TokenBankChallenge";
