// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IPriceFeed$Type } from "./IPriceFeed";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IPriceFeed"]: IPriceFeed$Type;
    ["contracts/interfaces/IPriceFeed.sol:IPriceFeed"]: IPriceFeed$Type;
  }

  interface ContractTypesMap {
    ["IPriceFeed"]: GetContractReturnType<IPriceFeed$Type["abi"]>;
    ["contracts/interfaces/IPriceFeed.sol:IPriceFeed"]: GetContractReturnType<IPriceFeed$Type["abi"]>;
  }
}
