// frontend/src/components/vaults/VaultData.ts
import { VaultData } from './VaultCard'; // Import the type from where it's defined

export const mockVaults: VaultData[] = [
  {
    id: "usdc-stable-yield",
    name: "USDC Stable Yield",
    description: "Low-risk strategy focused on stablecoin lending and liquidity provision.",
    apy: 5.25,
    tvl: 1_500_000,
    assets: ["USDC", "USDT"],
    riskLevel: "Low",
    contractAddress: "0x...",
  },
  {
    id: "dai-aggressive",
    name: "DAI Aggressive Growth",
    description: "Higher risk strategy involving liquidity provision and yield farming.",
    apy: 12.8,
    tvl: 5_500_000,
    assets: ["DAI"],
    riskLevel: "Medium",
    contractAddress: "0x...",
  },
  {
    id: "mixed-stable-balancer",
    name: "Mixed Stable Balancer",
    description: "Balances between multiple stablecoins for diversified yield sources.",
    apy: 6.80,
    tvl: 850_000,
    assets: ["USDC", "DAI", "USDT"],
    riskLevel: "Medium",
    contractAddress: "0x...",
  },
  {
    id: "eth-liquid-staking",
    name: "ETH Liquid Staking Yield",
    description: "Earn yield on ETH through liquid staking protocols like Lido or Rocket Pool.",
    apy: 4.10,
    tvl: 2_200_000,
    assets: ["ETH", "stETH"],
    riskLevel: "Low",
    contractAddress: "0x...",
  },
  {
    id: "wbtc-yield-farm",
    name: "WBTC Yield Farm",
    description: "Generate yield on Wrapped Bitcoin through various farming strategies.",
    apy: 7.50,
    tvl: 950_000,
    assets: ["WBTC", "ETH"],
    riskLevel: "Medium",
    contractAddress: "0x...",
  },
  {
    id: "arb-high-yield-alpha",
    name: "Arbitrum High-Yield Alpha",
    description: "Aggressive strategy on Arbitrum layer 2 seeking alpha through new protocols. Higher risk.",
    apy: 15.75,
    tvl: 350_000,
    assets: ["ETH", "ARB", "GMX"],
    riskLevel: "High",
    contractAddress: "0x...",
  },
  // --- Add New Low Risk Vaults Below ---
  {
    id: "gusd-stable-saver",
    name: "GUSD Stable Saver",
    description: "Basic low-risk lending strategy focused on Gemini Dollar (GUSD).",
    apy: 3.85,
    tvl: 650_000,
    assets: ["GUSD"],
    riskLevel: "Low",
    contractAddress: "0x...",
  },
  {
    id: "tusd-lending-optimizer",
    name: "TUSD Lending Optimizer",
    description: "Optimized lending across various platforms using TrueUSD (TUSD).",
    apy: 4.30,
    tvl: 1_100_000,
    assets: ["TUSD", "USDC"],
    riskLevel: "Low",
    contractAddress: "0x...",
  },
  // --- End of New Vaults ---
];
