/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface FiftyYearsChallengeInterface extends utils.Interface {
  functions: {
    "getValue(uint256)": FunctionFragment;
    "withdraw(uint256)": FunctionFragment;
    "upsert(uint256,uint256)": FunctionFragment;
    "getTotal()": FunctionFragment;
    "getLastItemTimestamp()": FunctionFragment;
    "isComplete()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getValue"
      | "withdraw"
      | "upsert"
      | "getTotal"
      | "getLastItemTimestamp"
      | "isComplete"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getValue",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "upsert",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "getTotal", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getLastItemTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isComplete",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "getValue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upsert", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTotal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLastItemTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isComplete", data: BytesLike): Result;

  events: {};
}

export interface FiftyYearsChallenge extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FiftyYearsChallengeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getValue(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdraw(
      index: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upsert(
      index: PromiseOrValue<BigNumberish>,
      timestamp: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getTotal(overrides?: CallOverrides): Promise<[BigNumber]>;

    getLastItemTimestamp(overrides?: CallOverrides): Promise<[BigNumber]>;

    isComplete(overrides?: CallOverrides): Promise<[boolean]>;
  };

  getValue(
    index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdraw(
    index: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upsert(
    index: PromiseOrValue<BigNumberish>,
    timestamp: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getTotal(overrides?: CallOverrides): Promise<BigNumber>;

  getLastItemTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

  isComplete(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    getValue(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    upsert(
      index: PromiseOrValue<BigNumberish>,
      timestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getTotal(overrides?: CallOverrides): Promise<BigNumber>;

    getLastItemTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    isComplete(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getValue(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      index: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upsert(
      index: PromiseOrValue<BigNumberish>,
      timestamp: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getTotal(overrides?: CallOverrides): Promise<BigNumber>;

    getLastItemTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    isComplete(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getValue(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      index: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upsert(
      index: PromiseOrValue<BigNumberish>,
      timestamp: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getTotal(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLastItemTimestamp(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isComplete(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
