/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GuessTheNewNumberAttacker } from "./GuessTheNewNumberAttacker";
export type { GuessTheNewNumberChallenge } from "./GuessTheNewNumberChallenge";
export type { IGuessTheNewNumber } from "./IGuessTheNewNumber";
