/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CaptureTheEther } from "./CaptureTheEther";
export type { NicknameChallenge } from "./NicknameChallenge";
