// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { LuminaCoin$Type } from "./LuminaCoin";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LuminaCoin"]: LuminaCoin$Type;
    ["contracts/LuminaCoin.sol:LuminaCoin"]: LuminaCoin$Type;
  }

  interface ContractTypesMap {
    ["LuminaCoin"]: GetContractReturnType<LuminaCoin$Type["abi"]>;
    ["contracts/LuminaCoin.sol:LuminaCoin"]: GetContractReturnType<LuminaCoin$Type["abi"]>;
  }
}
